dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    secure: ZPfKcJTzBqFmxHztxtaMJZXfPhJrks8BZWMoB9ta0l7PAjDUbdcaTC4PGcsADRz6+UAXFW0XwMSlEERUFfGEJBcjL4vuwgyu2JXSHaN0IKpvyYB6/Tx3sSg+P38QzbSq9mFHA4K8ibyfGaLSt0eMBeZl5e4aRAYEXTSGCul7rprysV8V0kVHo5xptVf6sJ3+7J3YuuTmeMVro5TRlpWaA2ZzbJr+JZSOq0bd+4wVJnyXmcgX9b5JPVfsAsPWpgg3YcJjt3enFlvbrwZwBw8yemKmfXFRpufG0/vqCSZ9oTXF2wbrjN6jo6DZiiZ6HaXG47pYAPNxlamPCvNvIRjEFROP52+Dkc65TnppMt+c3Y3Oy1FxKr2/Y3zpw7bdLyblxWJE2Hh27dwILvtgnttBBRnKXP9kAWUPeoO0Ob9/p1XQxOYjxV0VtqBo7oz1v51EJchqB9EkpBsbtm1v19mNgWs+EXR3DvSNFfPKHrmfWYhPAT5vCmx+u/lDdcwK88MGxeGCKfrwL+3G3FaD2yBjngUaOfM8QOX+JNmzgYa3u5f+6aRyShY9m6MJXsJ7lSTP9lowyzSJLjXgfASlnDrq1YUgetdvmAaq9ubqyGxJK1XkersYgZy3h8rthHzp8tsOu8eKeiGmt87AucWajH+S9grAADSF3nXiDpm8xGUPJdo=
