dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    secure: QoPf9wuvon6Og175gxqNhW+RK5xsIQhk9B1wl68fyyFnlmneHzZLrQ+oE3yeAMtGrOPux5T6Dm+ZJLJKjbvMlLd23UqDcp8do2iSTWoFz3lQ3C1t0bOU2aKRi94tHat7AdSvRXg/Gzg5im17IqiBH8GC/UR4+roTEVhgQPQycqlk1iYYpV0KkpdMYbBmq3wwzXH+83EZ+r8iTpT5j0dE/6YC4XBoQ0KVeOCAZOR3tqNDkpCoLHJD+07RqjaTsFw+usWKyL4ZtKUQ6pkYCSB0n4h7KdRuPobWTkKV8xO0ujMeqnX4xpze4TaVsZhzkSI8NDJHGtHEZxSEKTG2AMtYeZ5nqmmEi0j3wmRH7kpyp2uunp3AsMJUs1Vzmgzuz+NJcaFbs5R6y+i5QFSw1rxRvmQDWj05h5GgKT2w6SiF2TUUt3U17SqiTSpvdJXxsObm3fUbHjWxqQg15sNLi8YEWyNoFyLGpN9T5Af6yq2OjOdoOFXRLOHmi+JTwK73V6OpEWWjTGDzZZJpvIGUs/Rr/otgE7KxI2XNT6pFsXzrCHA53c7g5CFO3rmIDro4yZcVHVcDVNxTj5uG60BgFTSWD5OtGbU3DtttEuMCON/QpHMg0zuCh+8/b8MZ9JM7ZT0rOoa+MlvVLxkor7xIvYRSzKXWH8rCt00KT1RLO66s39I=
